name: check
on:
  pull_request:
  workflow_call:
  push:
    branches: [dev]
jobs:
  check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
        with:
          extra-conf: |
            accept-flake-config = true
            log-lines = 1000
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: mirkolenz
          authToken: ${{ secrets.CACHIX_TOKEN }}
      - run: nix flake check --show-trace
